//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BURegion
    {
        public int Id { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public int ParentId { get; set; }
        public Nullable<int> Bud_Win { get; set; }
        public Nullable<int> Core_Win { get; set; }
        public Nullable<int> UP { get; set; }
        public Nullable<int> Bud_TT { get; set; }
        public Nullable<int> Core_TT { get; set; }
    }
}
