//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tptoolkitEntities : DbContext
    {
        public tptoolkitEntities()
            : base("name=tptoolkitEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brand { get; set; }
        public virtual DbSet<BURegion> BURegion { get; set; }
        public virtual DbSet<ChannelType> ChannelType { get; set; }
        public virtual DbSet<MaterialGroup> MaterialGroup { get; set; }
        public virtual DbSet<MaterialItem> MaterialItem { get; set; }
        public virtual DbSet<NotifyMessage> NotifyMessage { get; set; }
        public virtual DbSet<Permission> Permission { get; set; }
        public virtual DbSet<RejectUserPic> RejectUserPic { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<RolePermission> RolePermission { get; set; }
        public virtual DbSet<SalePoint> SalePoint { get; set; }
        public virtual DbSet<SalePointFlow> SalePointFlow { get; set; }
        public virtual DbSet<SalePointPic> SalePointPic { get; set; }
        public virtual DbSet<SalePointType> SalePointType { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<UserFrom> UserFrom { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<UserVender> UserVender { get; set; }
        public virtual DbSet<Vender> Vender { get; set; }
        public virtual DbSet<VenderOrder> VenderOrder { get; set; }
        public virtual DbSet<QueryProgram> QueryProgram { get; set; }
        public virtual DbSet<QueryProgramBrand> QueryProgramBrand { get; set; }
        public virtual DbSet<QueryVender> QueryVender { get; set; }
        public virtual DbSet<SalePointsCompare> SalePointsCompare { get; set; }
        public virtual DbSet<SalePointsCompareCopy> SalePointsCompareCopy { get; set; }
    }
}
