//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryVender
    {
        public int venderid { get; set; }
        public string vendername { get; set; }
        public string manager { get; set; }
        public string phone { get; set; }
        public string bu { get; set; }
        public string region { get; set; }
        public string area { get; set; }
        public string office { get; set; }
    }
}
