//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePointsCompareCopy
    {
        public int Id { get; set; }
        public string ContractNo { get; set; }
        public string BU { get; set; }
        public string Region { get; set; }
        public string City { get; set; }
        public string ChannelType { get; set; }
        public string SalePointType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string M1 { get; set; }
        public string M2 { get; set; }
        public string M3 { get; set; }
        public string M4 { get; set; }
        public string Brand { get; set; }
        public string StartYearMonth { get; set; }
        public string EndYearMonth { get; set; }
        public Nullable<int> BeforeMonthCount { get; set; }
        public Nullable<int> TargetMonthCount { get; set; }
        public int Status { get; set; }
        public Nullable<bool> IsNewPoint { get; set; }
    }
}
