//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalePoint
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int CreatorId { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string WCCS { get; set; }
        public int SalePointTypeId { get; set; }
        public int ChannelTypeId { get; set; }
        public int UpTypesID { get; set; }
        public string MaterialStandard { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string M1 { get; set; }
        public string M2 { get; set; }
        public string M3 { get; set; }
        public string M4 { get; set; }
        public string Capacity { get; set; }
        public int Brand { get; set; }
        public string StartYearMonth { get; set; }
        public string Period { get; set; }
        public string EndYearMonth { get; set; }
        public string TerminationYearMonth { get; set; }
        public int VenderId { get; set; }
        public string Region { get; set; }
        public string BU { get; set; }
        public string ContractNo { get; set; }
        public string Code { get; set; }
        public bool IsHighEnd { get; set; }
        public int IsFinal { get; set; }
        public int IsMTBRefuseCount { get; set; }
    }
}
