//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string DisplayName { get; set; }
        public string Position { get; set; }
        public string OpenId { get; set; }
        public string BU { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public bool Deleted { get; set; }
        public string HeadUrl { get; set; }
        public string EmpNumber { get; set; }
        public string Phone { get; set; }
        public string Region { get; set; }
        public Nullable<int> SuperiorId { get; set; }
        public string FromID { get; set; }
    }
}
