//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDMX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VenderOrder
    {
        public int Id { get; set; }
        public int VenderId { get; set; }
        public int SalePointId { get; set; }
        public string StoreData { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string DesignPic { get; set; }
        public string OrderDoc { get; set; }
        public Nullable<int> Deleted { get; set; }
        public string score { get; set; }
    }
}
